name: Remote ssh command

on:
  workflow_run:
    workflows: ["Push-to-EC2"]
    types:
      - completed

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote ssh commands using ssh key
        uses: dhruv35m/portfolio-website@main
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /var/www/dhruvmishra.com/
            sudo npm run build
            sudo pm2 restart 87
