name: Push-to-EC2

# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on main branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Executing remote ssh commands using ssh key
        run: |
          ssh ${{ secrets.USERNAME }}@${{ secrets.HOST_DNS }} -i ${{ secrets.EC2_SSH_KEY }} << 'EOF'
          sudo apt-get -y update
          cd portfolio
          npm install
          npm run build
          sudo mv -f portfolio/dist /var/www/dhruvmishra/
          EOF
