name: Push-to-EC2

# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy to EC2 on main branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Executing remote ssh commands using ssh key
        uses: ./.github/workflows
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          target: ${{ secrets.TARGET_DIR }}
          script: |
            sudo apt-get -y update
            cd portfolio
            npm install
            npm run build
            sudo mv -f portfolio/dist /var/www/dhruvmishra/
