name: Push-to-EC2

# Trigger deployment only on push to master branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on main branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v3

      - name: code upload
        uses: easingthemes/ssh-deploy@main
        run: |
        rsync /home/runner/work/portfolio-website/portfolio-website/ ***@***:/var/www/dhruvmishra/portfolio/ --rsh "ssh -p 22 -i /home/runner/.ssh/deploy_key_***_1717941891783 -o StrictHostKeyChecking=no" --recursive --exclude= -rlgoDzvc -i --no-perms --chmod=ugo=rwX
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: /var/www/dhruvmishra/portfolio/
