name: Remote ssh command
on:
  workflow_run:
    workflows: ["Push-to-EC2"]
    types:
      - completed
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /var/www/dhruvmishra/portfolio/
            sudo /home/ubuntu/.nvm/versions/node/v21.7.2/bin/npm i
            sudo /home/ubuntu/.nvm/versions/node/v21.7.2/bin/npm run build
